name: msix_config_version_match
description: Simple utility to make the installer version in msix_config match the main pubspec version
version: 1.0.0

publish_to: none # For now

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 pubspec_parse: ^1.0.0
 pub_semver: ^2.0.0
 yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.11

